<a href="https://colab.research.google.com/github/Rajat262005/Ensemble-Learning/blob/main/Ensemble_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Random Forest

In [ ]:
#import libraries
from sklearn.datasets import load_iris
from sklearn.ensemble import RandomForestClassifier
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

In [ ]:
#Load Dataset
iris=load_iris()
x=iris.data
y=iris.target

In [ ]:
#split data
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

In [ ]:
#Train Random Forest
clf=RandomForestClassifier(n_estimators=100)
clf.fit(x_train,y_train)

RandomForestClassifier()

In [ ]:
#predict
y_pred=clf.predict(x_test)

In [ ]:
#Evaluate
print("confusion matrix;\n",confusion_matrix(y_test,y_pred))
print("classification report;\n",classification_report(y_test,y_pred))

confusion matrix;
 [[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
classification report;
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45



##Gradient Descent

In [ ]:
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

In [ ]:
data=fetch_california_housing()
x=data.data
y=data.target

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

In [ ]:
gbr=GradientBoostingRegressor(n_estimators=100,learning_rate=0.1,max_depth=3,random_state=42)
gbr.fit(x_train,y_train)

GradientBoostingRegressor(random_state=42)

In [ ]:
y_pred=gbr.predict(x_test)

In [ ]:
mse=mean_squared_error(y_test,y_pred)
r2=r2_score(y_test,y_pred)
print("Mean Squared Error:",mse)
print("R-squared:",r2)

Mean Squared Error: 0.28836337869645623
R-squared: 0.7803012822391022


##Adaboost

In [ ]:
from sklearn.datasets import load_iris
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [ ]:
#Load dataset
iris=load_iris()
x,y=iris.data,iris.target

In [ ]:
#use only two classses for binary classification
x=x[y!=2]
y=y[y!=2]

In [ ]:
#split data
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

In [ ]:
#Base esyimator
base_estimator=DecisionTreeClassifier(max_depth=1)

In [ ]:
#Train
# Use 'estimator' instead of 'base_estimator' in newer scikit-learn versions
ada = AdaBoostClassifier(estimator=base_estimator, n_estimators=50, learning_rate=1, random_state=42)
ada.fit(x_train, y_train)

AdaBoostClassifier(estimator=DecisionTreeClassifier(max_depth=1),
                   learning_rate=1, random_state=42)

In [ ]:
#predict
y_pred=ada.predict(x_test)

In [ ]:
#Evaluate
print("Accuracy;\n",accuracy_score(y_test,y_pred))
print("classification report;\n",classification_report(y_test,y_pred))

Accuracy;
 1.0
classification report;
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        17
           1       1.00      1.00      1.00        13

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

